In [1]:
import numpy as np

In [2]:
# === Layer 1 ===
W1 = np.array([[0.10, -0.20],
               [0.30,  0.05]])
b1 = np.array([[0.00],
               [0.00]])

# === Layer 2 ===
W2 = np.array([[0.02, -0.04],
               [-0.03, 0.06]])
b2 = np.array([[0.01],
               [-0.02]])

# === Layer 3 ===
W3 = np.array([[0.08, -0.05, 0.02],
               [-0.04, 0.07, 0.03]]).T
b3 = np.array([[0.00],
               [0.00],
               [0.00]])

# Dataset D
X = np.array([[-1.0,  1.0, 2.0],
              [ 1.5, -1.0, 0.5]], dtype=float)  # shape: (2, N)
y = np.array([0, 1, 2], dtype=int)              # shape: (N,)

In [3]:
# 系統參數
lr = 0.05
epochs = 5

In [4]:
np.set_printoptions(precision=8, suppress=True)
N = X.shape[1]

# 工具函式
# -----------------------------
def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))

def softmax(z):
    # column-wise softmax（每一筆樣本一欄）
    z_stable = z - np.max(z, axis=0, keepdims=True)
    exp_z = np.exp(z_stable)
    return exp_z / np.sum(exp_z, axis=0, keepdims=True)

def one_hot(y, num_classes):
    Y = np.zeros((num_classes, y.size))
    Y[y, np.arange(y.size)] = 1.0
    return Y

def cross_entropy_avg(p, y_onehot):
    # 平均 cross-entropy（batch 平均）
    eps = 1e-12 # 防止log(0)發生，避免數值錯誤
    return -np.sum(y_onehot * np.log(p + eps)) / y_onehot.shape[1]

Y = one_hot(y, num_classes=3)

# -----------------------------
# 訓練（Full-batch GD）
# -----------------------------
for epoch in range(1, epochs + 1):
    # ---- Forward ----
    z1 = W1 @ X + b1                   # (2,N)
    a1 = sigmoid(z1)                   # (2,N)

    z2 = W2 @ a1 + b2                  # (2,N)
    a2 = sigmoid(z2)                   # (2,N)

    z3 = W3 @ a2 + b3                  # (3,N)
    p  = softmax(z3)                   # (3,N)

    loss = cross_entropy_avg(p, Y)

    # ---- Backward ----
    # Softmax + CE：dz3 = (p - Y)/N
    dz3 = (p - Y) / N                  # (3,N)
    dW3 = dz3 @ a2.T                   # (3,2)
    db3 = np.sum(dz3, axis=1, keepdims=True)  # (3,1)

    da2 = W3.T @ dz3                   # (2,N)
    dz2 = da2 * a2 * (1 - a2)          # (2,N)
    dW2 = dz2 @ a1.T                   # (2,2)
    db2 = np.sum(dz2, axis=1, keepdims=True)  # (2,1)

    da1 = W2.T @ dz2                   # (2,N)
    dz1 = da1 * a1 * (1 - a1)          # (2,N)
    dW1 = dz1 @ X.T                    # (2,2)
    db1 = np.sum(dz1, axis=1, keepdims=True)  # (2,1)

    # ---- Gradient Descent Update ----
    W3 -= lr * dW3
    b3 -= lr * db3
    W2 -= lr * dW2
    b2 -= lr * db2
    W1 -= lr * dW1
    b1 -= lr * db1

    # ---- 記錄輸出 ----
    print(f"Epoch {epoch}: Loss = {loss:.6f}")
    print("W1 =\n", W1)
    print("b1 =", b1.ravel())
    print("W2 =\n", W2)
    print("b2 =", b2.ravel())
    print("W3 =\n", W3)
    print("b3 =", b3.ravel())
    print("-" * 55)


Epoch 1: Loss = 1.098611
W1 =
 [[ 0.09999354 -0.19999264]
 [ 0.30001304  0.04998496]]
b1 = [-0.00000009 -0.        ]
W2 =
 [[ 0.01995221 -0.04003151]
 [-0.02995785  0.06003429]]
b2 = [ 0.00999717 -0.01999814]
W3 =
 [[ 0.07999616 -0.04002844]
 [-0.04992628  0.0700623 ]
 [ 0.01993012  0.02996615]]
b3 = [-0.00002739  0.00013844 -0.00011105]
-------------------------------------------------------
Epoch 2: Loss = 1.098610
W1 =
 [[ 0.09998709 -0.19998529]
 [ 0.30002608  0.04996992]]
b1 = [-0.00000017 -0.        ]
W2 =
 [[ 0.01990448 -0.04006301]
 [-0.02991569  0.06006856]]
b2 = [ 0.00999441 -0.01999631]
W3 =
 [[ 0.07999272 -0.04005656]
 [-0.0498543   0.07012289]
 [ 0.01986158  0.02993367]]
b3 = [-0.00005404  0.00027343 -0.00021938]
-------------------------------------------------------
Epoch 3: Loss = 1.098609
W1 =
 [[ 0.09998065 -0.19997795]
 [ 0.30003914  0.04995485]]
b1 = [-0.00000026 -0.00000001]
W2 =
 [[ 0.0198568  -0.0400945 ]
 [-0.02987353  0.06010281]]
b2 = [ 0.00999172 -0.01999454]